# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/v1a3g/setup-makefiles.sh

VENDOR_DIR := vendor/samsung/v1a3g/proprietary

# app/mcRegistry # Mobicore
# Mobicore
PRODUCT_COPY_FILES += \
    $(VENDOR_DIR)/app/mcRegistry/00060308060501020000000000000000.tlbin:system/app/mcRegistry/00060308060501020000000000000000.tlbin \
    $(VENDOR_DIR)/app/mcRegistry/02010000080300030000000000000000.tlbin:system/app/mcRegistry/02010000080300030000000000000000.tlbin \
    $(VENDOR_DIR)/app/mcRegistry/07010000000000000000000000000000.tlbin:system/app/mcRegistry/07010000000000000000000000000000.tlbin \
    $(VENDOR_DIR)/app/mcRegistry/07060000000000000000000000000000.tlbin:system/app/mcRegistry/07060000000000000000000000000000.tlbin \
    $(VENDOR_DIR)/app/mcRegistry/ffffffff000000000000000000000003.tlbin:system/app/mcRegistry/ffffffff000000000000000000000003.tlbin \
    $(VENDOR_DIR)/app/mcRegistry/ffffffff000000000000000000000004.tlbin:system/app/mcRegistry/ffffffff000000000000000000000004.tlbin \
    $(VENDOR_DIR)/app/mcRegistry/ffffffff000000000000000000000005.tlbin:system/app/mcRegistry/ffffffff000000000000000000000005.tlbin \
    $(VENDOR_DIR)/app/mcRegistry/ffffffff000000000000000000000007.tlbin:system/app/mcRegistry/ffffffff000000000000000000000007.tlbin \
    $(VENDOR_DIR)/app/mcRegistry/ffffffff000000000000000000000008.tlbin:system/app/mcRegistry/ffffffff000000000000000000000008.tlbin \
    $(VENDOR_DIR)/app/mcRegistry/ffffffff000000000000000000000009.tlbin:system/app/mcRegistry/ffffffff000000000000000000000009.tlbin \
    $(VENDOR_DIR)/app/mcRegistry/ffffffff000000000000000000000010.tlbin:system/app/mcRegistry/ffffffff000000000000000000000010.tlbin \
    $(VENDOR_DIR)/app/mcRegistry/ffffffff000000000000000000000011.tlbin:system/app/mcRegistry/ffffffff000000000000000000000011.tlbin \
    $(VENDOR_DIR)/app/mcRegistry/ffffffff000000000000000000000012.tlbin:system/app/mcRegistry/ffffffff000000000000000000000012.tlbin \
    $(VENDOR_DIR)/app/mcRegistry/ffffffff000000000000000000000013.tlbin:system/app/mcRegistry/ffffffff000000000000000000000013.tlbin \
    $(VENDOR_DIR)/app/mcRegistry/ffffffff000000000000000000000017.tlbin:system/app/mcRegistry/ffffffff000000000000000000000017.tlbin \
    $(VENDOR_DIR)/app/mcRegistry/ffffffff000000000000000000000018.tlbin:system/app/mcRegistry/ffffffff000000000000000000000018.tlbin \
    $(VENDOR_DIR)/app/mcRegistry/ffffffff00000000000000000000000a.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000a.tlbin \
    $(VENDOR_DIR)/app/mcRegistry/ffffffff00000000000000000000000b.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000b.tlbin \
    $(VENDOR_DIR)/app/mcRegistry/ffffffff00000000000000000000000c.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000c.tlbin \
    $(VENDOR_DIR)/app/mcRegistry/ffffffff00000000000000000000000d.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000d.tlbin \
    $(VENDOR_DIR)/app/mcRegistry/ffffffff00000000000000000000000e.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000e.tlbin \
    $(VENDOR_DIR)/app/mcRegistry/ffffffff00000000000000000000000f.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000f.tlbin \
    $(VENDOR_DIR)/app/mcRegistry/ffffffffd00000000000000000000004.tlbin:system/app/mcRegistry/ffffffffd00000000000000000000004.tlbin \
    $(VENDOR_DIR)/app/mcRegistry/ffffffffd0000000000000000000000a.tlbin:system/app/mcRegistry/ffffffffd0000000000000000000000a.tlbin \
    $(VENDOR_DIR)/app/mcRegistry/ffffffffd0000000000000000000000e.tlbin:system/app/mcRegistry/ffffffffd0000000000000000000000e.tlbin \
    $(VENDOR_DIR)/app/mcRegistry/fffffffff0000000000000000000001e.tlbin:system/app/mcRegistry/fffffffff0000000000000000000001e.tlbin

# app
PRODUCT_COPY_FILES += \
    $(VENDOR_DIR)/app/FFFFFFFF000000000000000000000001.drbin:system/app/FFFFFFFF000000000000000000000001.drbin

# bin
PRODUCT_COPY_FILES += \
    $(VENDOR_DIR)/bin/cbd:system/bin/cbd \
    $(VENDOR_DIR)/bin/cs:system/bin/cs \
    $(VENDOR_DIR)/bin/gps.cer:system/bin/gps.cer \
    $(VENDOR_DIR)/bin/gpsd:system/bin/gpsd

# etc/permissions
PRODUCT_COPY_FILES += \
    $(VENDOR_DIR)/etc/permissions/com.samsung.device.xml:system/etc/permissions/com.samsung.device.xml \
    $(VENDOR_DIR)/etc/permissions/com.sec.feature.spen_usp_level3.xml:system/etc/permissions/com.sec.feature.spen_usp_level3.xml \
    $(VENDOR_DIR)/etc/permissions/com.sec.feature.wfd_support.xml:system/etc/permissions/com.sec.feature.wfd_support.xml

# WiFi - Firmware
PRODUCT_COPY_FILES += \
    $(VENDOR_DIR)/etc/wifi/bcmdhd_apsta.bin:system/etc/wifi/bcmdhd_apsta.bin \
    $(VENDOR_DIR)/etc/wifi/bcmdhd_ibss.bin:system/etc/wifi/bcmdhd_ibss.bin \
    $(VENDOR_DIR)/etc/wifi/bcmdhd_mfg.bin:system/etc/wifi/bcmdhd_mfg.bin \
    $(VENDOR_DIR)/etc/wifi/bcmdhd_sta.bin:system/etc/wifi/bcmdhd_sta.bin \
    $(VENDOR_DIR)/etc/wifi/bcmdhd_apsta.bin_a0:system/etc/wifi/bcmdhd_apsta.bin_a0 \
    $(VENDOR_DIR)/etc/wifi/bcmdhd_ibss.bin_a0:system/etc/wifi/bcmdhd_ibss.bin_a0 \
    $(VENDOR_DIR)/etc/wifi/bcmdhd_mfg.bin_a0:system/etc/wifi/bcmdhd_mfg.bin_a0 \
    $(VENDOR_DIR)/etc/wifi/bcmdhd_sta.bin_a0:system/etc/wifi/bcmdhd_sta.bin_a0 \
    $(VENDOR_DIR)/etc/wifi/bcmdhd_apsta.bin_4339_a0:system/etc/wifi/bcmdhd_apsta.bin_4339_a0 \
    $(VENDOR_DIR)/etc/wifi/bcmdhd_ibss.bin_4339_a0:system/etc/wifi/bcmdhd_ibss.bin_4339_a0 \
    $(VENDOR_DIR)/etc/wifi/bcmdhd_mfg.bin_4339_a0:system/etc/wifi/bcmdhd_mfg.bin_4339_a0 \
    $(VENDOR_DIR)/etc/wifi/bcmdhd_sta.bin_4339_a0:system/etc/wifi/bcmdhd_sta.bin_4339_a0 \
    $(VENDOR_DIR)/etc/wifi/bcmdhd_apsta.bin_4354_a0:system/etc/wifi/bcmdhd_apsta.bin_4354_a0 \
    $(VENDOR_DIR)/etc/wifi/bcmdhd_ibss.bin_4354_a0:system/etc/wifi/bcmdhd_ibss.bin_4354_a0 \
    $(VENDOR_DIR)/etc/wifi/bcmdhd_mfg.bin_4354_a0:system/etc/wifi/bcmdhd_mfg.bin_4354_a0 \
    $(VENDOR_DIR)/etc/wifi/bcmdhd_sta.bin_4354_a0:system/etc/wifi/bcmdhd_sta.bin_4354_a0 \
    $(VENDOR_DIR)/etc/wifi/bcmdhd_apsta.bin_4354_a1:system/etc/wifi/bcmdhd_apsta.bin_4354_a1 \
    $(VENDOR_DIR)/etc/wifi/bcmdhd_ibss.bin_4354_a1:system/etc/wifi/bcmdhd_ibss.bin_4354_a1 \
    $(VENDOR_DIR)/etc/wifi/bcmdhd_mfg.bin_4354_a1:system/etc/wifi/bcmdhd_mfg.bin_4354_a1 \
    $(VENDOR_DIR)/etc/wifi/bcmdhd_sta.bin_4354_a1:system/etc/wifi/bcmdhd_sta.bin_4354_a1 \
    $(VENDOR_DIR)/etc/wifi/cred.conf:system/etc/wifi/cred.conf \
    $(VENDOR_DIR)/etc/wifi/nvram_mfg.txt_4339_a0:system/etc/wifi/nvram_mfg.txt_4339_a0 \
    $(VENDOR_DIR)/etc/wifi/nvram_net.txt_4339_a0:system/etc/wifi/nvram_net.txt_4339_a0 \
    $(VENDOR_DIR)/etc/wifi/nvram_mfg.txt_4354_a0:system/etc/wifi/nvram_mfg.txt_4354_a0 \
    $(VENDOR_DIR)/etc/wifi/nvram_net.txt_4354_a0:system/etc/wifi/nvram_net.txt_4354_a0 \
    $(VENDOR_DIR)/etc/wifi/nvram_mfg.txt_4354_a1:system/etc/wifi/nvram_mfg.txt_4354_a1 \
    $(VENDOR_DIR)/etc/wifi/nvram_net.txt_4354_a1:system/etc/wifi/nvram_net.txt_4354_a1 \
    $(VENDOR_DIR)/etc/wifi/olsrd.conf:system/etc/wifi/olsrd.conf

# etc
PRODUCT_COPY_FILES += \
    $(VENDOR_DIR)/etc/PARAM.ini:system/etc/PARAM.ini \
    $(VENDOR_DIR)/etc/PDC.ini:system/etc/PDC.ini \
    $(VENDOR_DIR)/etc/gps.conf:system/etc/gps.conf \
    $(VENDOR_DIR)/etc/gps.xml:system/etc/gps.xml \
    $(VENDOR_DIR)/etc/plmn_se13.bin:system/etc/plmn_se13.bin \
    $(VENDOR_DIR)/etc/srm.bin:system/etc/srm.bin

# framework
PRODUCT_COPY_FILES += \
    $(VENDOR_DIR)/framework/com.samsung.device.jar:system/framework/com.samsung.device.jar

# lib/hw
PRODUCT_COPY_FILES += \
    $(VENDOR_DIR)/lib/hw/gps.universal5420.so:system/lib/hw/gps.universal5420.so \
    $(VENDOR_DIR)/lib/hw/sensors.universal5420.so:system/lib/hw/sensors.universal5420.so

# lib/omx
PRODUCT_COPY_FILES += \
    $(VENDOR_DIR)/lib/omx/libOMX.Exynos.AVC.Encoder.so:system/lib/omx/libOMX.Exynos.AVC.Encoder.so

# lib
PRODUCT_COPY_FILES += \
    $(VENDOR_DIR)/lib/libGLES_trace.so:system/lib/libGLES_trace.so \
    $(VENDOR_DIR)/lib/libak8963c.so:system/lib/libak8963c.so \
    $(VENDOR_DIR)/lib/libexynoscamera.so:system/lib/libexynoscamera.so \
    $(VENDOR_DIR)/lib/libsec-ril.so:system/lib/libsec-ril.so \
    $(VENDOR_DIR)/lib/libvdis.so:system/lib/libvdis.so \
    $(VENDOR_DIR)/lib/libwrappergps.so:system/lib/libwrappergps.so

# vendor/firmware
# Samsung Exynos5 SoC series FIMC-IS driver firmware
PRODUCT_COPY_FILES += \
    $(VENDOR_DIR)/vendor/firmware/fimc_is_fw2_IMX134.bin:system/vendor/firmware/fimc_is_fw2_IMX134.bin \
    $(VENDOR_DIR)/vendor/firmware/mfc_fw.bin:system/vendor/firmware/mfc_fw.bin \
    $(VENDOR_DIR)/vendor/firmware/setfile_6b2.bin:system/vendor/firmware/setfile_6b2.bin \
    $(VENDOR_DIR)/vendor/firmware/setfile_imx134.bin:system/vendor/firmware/setfile_imx134.bin \
    $(VENDOR_DIR)/vendor/firmware/srp_cga.bin:system/vendor/firmware/srp_cga.bin \
    $(VENDOR_DIR)/vendor/firmware/srp_data.bin:system/vendor/firmware/srp_data.bin \
    $(VENDOR_DIR)/vendor/firmware/srp_vliw.bin:system/vendor/firmware/srp_vliw.bin

# Bluetooth
# Bluetooth
PRODUCT_COPY_FILES += \
    $(VENDOR_DIR)/vendor/firmware/bcm4335_V0105.0552.hcd:system/vendor/firmware/bcm4335_V0105.0552.hcd \
    $(VENDOR_DIR)/vendor/firmware/bcm4350_V0301.0670.hcd:system/vendor/firmware/bcm4350_V0301.0670.hcd

# vendor/lib/egl
# OpenGL - T6XX R7P0 GPU Driver
PRODUCT_COPY_FILES += \
    $(VENDOR_DIR)/vendor/lib/egl/libGLES_mali.so:system/vendor/lib/egl/libGLES_mali.so

# vendor/lib/mediadrm
PRODUCT_COPY_FILES += \
    $(VENDOR_DIR)/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so

# vendor/lib
# RS - T6XX R7P0 GPU Driver
PRODUCT_COPY_FILES += \
    $(VENDOR_DIR)/vendor/lib/libmalicore.bc:system/vendor/lib/libmalicore.bc

# Noise Suppression Controller
PRODUCT_COPY_FILES += \
    $(VENDOR_DIR)/vendor/lib/liblvverx_3.25.00.so:system/vendor/lib/liblvverx.so \
    $(VENDOR_DIR)/vendor/lib/liblvvetx_3.25.00.so:system/vendor/lib/liblvvetx.so

# Noise Suppression
PRODUCT_COPY_FILES += \
    $(VENDOR_DIR)/vendor/etc/nxp/BargeInDriving/Tx_ControlParams_WIDEBAND_WIRED_HEADSET.txt:system/vendor/etc/nxp/BargeInDriving/Tx_ControlParams_WIDEBAND_WIRED_HEADSET.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/BargeInDriving/Tx_ControlParams_WIDEBAND_ANALOG_DOCK.txt:system/vendor/etc/nxp/BargeInDriving/Tx_ControlParams_WIDEBAND_ANALOG_DOCK.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/BargeInDriving/Tx_ControlParams_WIDEBAND_BLUETOOTH_SCO_HEADSET.txt:system/vendor/etc/nxp/BargeInDriving/Tx_ControlParams_WIDEBAND_BLUETOOTH_SCO_HEADSET.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/BargeInDriving/Tx_ControlParams_WIDEBAND_SPEAKER.txt:system/vendor/etc/nxp/BargeInDriving/Tx_ControlParams_WIDEBAND_SPEAKER.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/BargeInDriving/Tx_ControlParams_WIDEBAND_EARPIECE.txt:system/vendor/etc/nxp/BargeInDriving/Tx_ControlParams_WIDEBAND_EARPIECE.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/BargeInDriving/Tx_ControlParams_WIDEBAND_WIRED_HEADPHONE.txt:system/vendor/etc/nxp/BargeInDriving/Tx_ControlParams_WIDEBAND_WIRED_HEADPHONE.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/mVoIPFMC/Rx_ControlParams_WIDEBAND_WIRED_HEADPHONE.txt:system/vendor/etc/nxp/mVoIPFMC/Rx_ControlParams_WIDEBAND_WIRED_HEADPHONE.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/mVoIPFMC/Rx_ControlParams_WIDEBAND_BLUETOOTH_SCO_HEADSET.txt:system/vendor/etc/nxp/mVoIPFMC/Rx_ControlParams_WIDEBAND_BLUETOOTH_SCO_HEADSET.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/mVoIPFMC/Rx_ControlParams_WIDEBAND_SPEAKER.txt:system/vendor/etc/nxp/mVoIPFMC/Rx_ControlParams_WIDEBAND_SPEAKER.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/mVoIPFMC/Tx_ControlParams_WIDEBAND_WIRED_HEADSET.txt:system/vendor/etc/nxp/mVoIPFMC/Tx_ControlParams_WIDEBAND_WIRED_HEADSET.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/mVoIPFMC/Tx_ControlParams_WIDEBAND_BLUETOOTH_SCO_HEADSET.txt:system/vendor/etc/nxp/mVoIPFMC/Tx_ControlParams_WIDEBAND_BLUETOOTH_SCO_HEADSET.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/mVoIPFMC/Tx_ControlParams_WIDEBAND_SPEAKER.txt:system/vendor/etc/nxp/mVoIPFMC/Tx_ControlParams_WIDEBAND_SPEAKER.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/mVoIPFMC/Rx_ControlParams_WIDEBAND_WIRED_HEADSET.txt:system/vendor/etc/nxp/mVoIPFMC/Rx_ControlParams_WIDEBAND_WIRED_HEADSET.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/mVoIPFMC/Tx_ControlParams_WIDEBAND_EARPIECE.txt:system/vendor/etc/nxp/mVoIPFMC/Tx_ControlParams_WIDEBAND_EARPIECE.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/mVoIPFMC/Rx_ControlParams_WIDEBAND_EARPIECE.txt:system/vendor/etc/nxp/mVoIPFMC/Rx_ControlParams_WIDEBAND_EARPIECE.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/mVoIPFMC/Tx_ControlParams_WIDEBAND_WIRED_HEADPHONE.txt:system/vendor/etc/nxp/mVoIPFMC/Tx_ControlParams_WIDEBAND_WIRED_HEADPHONE.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/LVVEFS_Tx_Configuration.txt:system/vendor/etc/nxp/LVVEFS_Tx_Configuration.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/mVoIPSec/Rx_ControlParams_WIDEBAND_WIRED_HEADPHONE.txt:system/vendor/etc/nxp/mVoIPSec/Rx_ControlParams_WIDEBAND_WIRED_HEADPHONE.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/mVoIPSec/Rx_ControlParams_WIDEBAND_BLUETOOTH_SCO_HEADSET.txt:system/vendor/etc/nxp/mVoIPSec/Rx_ControlParams_WIDEBAND_BLUETOOTH_SCO_HEADSET.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/mVoIPSec/Rx_ControlParams_WIDEBAND_SPEAKER.txt:system/vendor/etc/nxp/mVoIPSec/Rx_ControlParams_WIDEBAND_SPEAKER.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/mVoIPSec/Tx_ControlParams_WIDEBAND_WIRED_HEADSET.txt:system/vendor/etc/nxp/mVoIPSec/Tx_ControlParams_WIDEBAND_WIRED_HEADSET.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/mVoIPSec/Tx_ControlParams_WIDEBAND_BLUETOOTH_SCO_HEADSET.txt:system/vendor/etc/nxp/mVoIPSec/Tx_ControlParams_WIDEBAND_BLUETOOTH_SCO_HEADSET.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/mVoIPSec/Tx_ControlParams_WIDEBAND_SPEAKER.txt:system/vendor/etc/nxp/mVoIPSec/Tx_ControlParams_WIDEBAND_SPEAKER.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/mVoIPSec/Rx_ControlParams_WIDEBAND_WIRED_HEADSET.txt:system/vendor/etc/nxp/mVoIPSec/Rx_ControlParams_WIDEBAND_WIRED_HEADSET.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/mVoIPSec/Tx_ControlParams_WIDEBAND_EARPIECE.txt:system/vendor/etc/nxp/mVoIPSec/Tx_ControlParams_WIDEBAND_EARPIECE.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/mVoIPSec/Rx_ControlParams_WIDEBAND_EARPIECE.txt:system/vendor/etc/nxp/mVoIPSec/Rx_ControlParams_WIDEBAND_EARPIECE.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/mVoIPSec/Tx_ControlParams_WIDEBAND_WIRED_HEADPHONE.txt:system/vendor/etc/nxp/mVoIPSec/Tx_ControlParams_WIDEBAND_WIRED_HEADPHONE.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/mVoIP/Rx_ControlParams_WIDEBAND_WIRED_HEADPHONE.txt:system/vendor/etc/nxp/mVoIP/Rx_ControlParams_WIDEBAND_WIRED_HEADPHONE.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/mVoIP/Rx_ControlParams_WIDEBAND_BLUETOOTH_SCO_HEADSET.txt:system/vendor/etc/nxp/mVoIP/Rx_ControlParams_WIDEBAND_BLUETOOTH_SCO_HEADSET.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/mVoIP/Tx_ControlParams_NARROWBAND_SPEAKER.txt:system/vendor/etc/nxp/mVoIP/Tx_ControlParams_NARROWBAND_SPEAKER.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/mVoIP/Tx_ControlParams_NARROWBAND_WIRED_HEADPHONE.txt:system/vendor/etc/nxp/mVoIP/Tx_ControlParams_NARROWBAND_WIRED_HEADPHONE.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/mVoIP/Rx_ControlParams_WIDEBAND_SPEAKER.txt:system/vendor/etc/nxp/mVoIP/Rx_ControlParams_WIDEBAND_SPEAKER.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/mVoIP/Rx_ControlParams_NARROWBAND_SPEAKER.txt:system/vendor/etc/nxp/mVoIP/Rx_ControlParams_NARROWBAND_SPEAKER.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/mVoIP/Tx_ControlParams_NARROWBAND_EARPIECE.txt:system/vendor/etc/nxp/mVoIP/Tx_ControlParams_NARROWBAND_EARPIECE.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/mVoIP/Tx_ControlParams_WIDEBAND_WIRED_HEADSET.txt:system/vendor/etc/nxp/mVoIP/Tx_ControlParams_WIDEBAND_WIRED_HEADSET.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/mVoIP/Tx_ControlParams_NARROWBAND_BLUETOOTH_SCO_HEADSET.txt:system/vendor/etc/nxp/mVoIP/Tx_ControlParams_NARROWBAND_BLUETOOTH_SCO_HEADSET.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/mVoIP/Tx_ControlParams_WIDEBAND_BLUETOOTH_SCO_HEADSET.txt:system/vendor/etc/nxp/mVoIP/Tx_ControlParams_WIDEBAND_BLUETOOTH_SCO_HEADSET.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/mVoIP/Rx_ControlParams_NARROWBAND_BLUETOOTH_SCO_HEADSET.txt:system/vendor/etc/nxp/mVoIP/Rx_ControlParams_NARROWBAND_BLUETOOTH_SCO_HEADSET.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/mVoIP/Tx_ControlParams_WIDEBAND_SPEAKER.txt:system/vendor/etc/nxp/mVoIP/Tx_ControlParams_WIDEBAND_SPEAKER.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/mVoIP/Rx_ControlParams_WIDEBAND_WIRED_HEADSET.txt:system/vendor/etc/nxp/mVoIP/Rx_ControlParams_WIDEBAND_WIRED_HEADSET.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/mVoIP/Rx_ControlParams_NARROWBAND_EARPIECE.txt:system/vendor/etc/nxp/mVoIP/Rx_ControlParams_NARROWBAND_EARPIECE.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/mVoIP/Rx_ControlParams_NARROWBAND_WIRED_HEADSET.txt:system/vendor/etc/nxp/mVoIP/Rx_ControlParams_NARROWBAND_WIRED_HEADSET.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/mVoIP/Tx_ControlParams_NARROWBAND_WIRED_HEADSET.txt:system/vendor/etc/nxp/mVoIP/Tx_ControlParams_NARROWBAND_WIRED_HEADSET.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/mVoIP/Rx_ControlParams_NARROWBAND_WIRED_HEADPHONE.txt:system/vendor/etc/nxp/mVoIP/Rx_ControlParams_NARROWBAND_WIRED_HEADPHONE.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/mVoIP/Tx_ControlParams_WIDEBAND_EARPIECE.txt:system/vendor/etc/nxp/mVoIP/Tx_ControlParams_WIDEBAND_EARPIECE.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/mVoIP/Rx_ControlParams_WIDEBAND_EARPIECE.txt:system/vendor/etc/nxp/mVoIP/Rx_ControlParams_WIDEBAND_EARPIECE.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/mVoIP/Tx_ControlParams_WIDEBAND_WIRED_HEADPHONE.txt:system/vendor/etc/nxp/mVoIP/Tx_ControlParams_WIDEBAND_WIRED_HEADPHONE.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/LVVEFS_Rx_Configuration.txt:system/vendor/etc/nxp/LVVEFS_Rx_Configuration.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/VideoTelephony/Rx_ControlParams_WIDEBAND_WIRED_HEADPHONE.txt:system/vendor/etc/nxp/VideoTelephony/Rx_ControlParams_WIDEBAND_WIRED_HEADPHONE.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/VideoTelephony/Rx_ControlParams_WIDEBAND_BLUETOOTH_SCO_HEADSET.txt:system/vendor/etc/nxp/VideoTelephony/Rx_ControlParams_WIDEBAND_BLUETOOTH_SCO_HEADSET.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/VideoTelephony/Tx_ControlParams_NARROWBAND_SPEAKER.txt:system/vendor/etc/nxp/VideoTelephony/Tx_ControlParams_NARROWBAND_SPEAKER.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/VideoTelephony/Tx_ControlParams_NARROWBAND_WIRED_HEADPHONE.txt:system/vendor/etc/nxp/VideoTelephony/Tx_ControlParams_NARROWBAND_WIRED_HEADPHONE.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/VideoTelephony/Rx_ControlParams_WIDEBAND_SPEAKER.txt:system/vendor/etc/nxp/VideoTelephony/Rx_ControlParams_WIDEBAND_SPEAKER.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/VideoTelephony/Rx_ControlParams_NARROWBAND_SPEAKER.txt:system/vendor/etc/nxp/VideoTelephony/Rx_ControlParams_NARROWBAND_SPEAKER.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/VideoTelephony/Tx_ControlParams_NARROWBAND_EARPIECE.txt:system/vendor/etc/nxp/VideoTelephony/Tx_ControlParams_NARROWBAND_EARPIECE.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/VideoTelephony/Tx_ControlParams_WIDEBAND_WIRED_HEADSET.txt:system/vendor/etc/nxp/VideoTelephony/Tx_ControlParams_WIDEBAND_WIRED_HEADSET.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/VideoTelephony/Tx_ControlParams_NARROWBAND_BLUETOOTH_SCO_HEADSET.txt:system/vendor/etc/nxp/VideoTelephony/Tx_ControlParams_NARROWBAND_BLUETOOTH_SCO_HEADSET.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/VideoTelephony/Tx_ControlParams_WIDEBAND_BLUETOOTH_SCO_HEADSET.txt:system/vendor/etc/nxp/VideoTelephony/Tx_ControlParams_WIDEBAND_BLUETOOTH_SCO_HEADSET.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/VideoTelephony/Rx_ControlParams_NARROWBAND_BLUETOOTH_SCO_HEADSET.txt:system/vendor/etc/nxp/VideoTelephony/Rx_ControlParams_NARROWBAND_BLUETOOTH_SCO_HEADSET.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/VideoTelephony/Tx_ControlParams_WIDEBAND_SPEAKER.txt:system/vendor/etc/nxp/VideoTelephony/Tx_ControlParams_WIDEBAND_SPEAKER.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/VideoTelephony/Rx_ControlParams_WIDEBAND_WIRED_HEADSET.txt:system/vendor/etc/nxp/VideoTelephony/Rx_ControlParams_WIDEBAND_WIRED_HEADSET.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/VideoTelephony/Rx_ControlParams_NARROWBAND_EARPIECE.txt:system/vendor/etc/nxp/VideoTelephony/Rx_ControlParams_NARROWBAND_EARPIECE.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/VideoTelephony/Rx_ControlParams_NARROWBAND_WIRED_HEADSET.txt:system/vendor/etc/nxp/VideoTelephony/Rx_ControlParams_NARROWBAND_WIRED_HEADSET.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/VideoTelephony/Tx_ControlParams_NARROWBAND_WIRED_HEADSET.txt:system/vendor/etc/nxp/VideoTelephony/Tx_ControlParams_NARROWBAND_WIRED_HEADSET.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/VideoTelephony/Rx_ControlParams_NARROWBAND_WIRED_HEADPHONE.txt:system/vendor/etc/nxp/VideoTelephony/Rx_ControlParams_NARROWBAND_WIRED_HEADPHONE.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/VideoTelephony/Tx_ControlParams_WIDEBAND_EARPIECE.txt:system/vendor/etc/nxp/VideoTelephony/Tx_ControlParams_WIDEBAND_EARPIECE.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/VideoTelephony/Rx_ControlParams_WIDEBAND_EARPIECE.txt:system/vendor/etc/nxp/VideoTelephony/Rx_ControlParams_WIDEBAND_EARPIECE.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/VideoTelephony/Tx_ControlParams_WIDEBAND_WIRED_HEADPHONE.txt:system/vendor/etc/nxp/VideoTelephony/Tx_ControlParams_WIDEBAND_WIRED_HEADPHONE.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/BargeIn/Tx_ControlParams_WIDEBAND_WIRED_HEADSET.txt:system/vendor/etc/nxp/BargeIn/Tx_ControlParams_WIDEBAND_WIRED_HEADSET.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/BargeIn/Tx_ControlParams_WIDEBAND_ANALOG_DOCK.txt:system/vendor/etc/nxp/BargeIn/Tx_ControlParams_WIDEBAND_ANALOG_DOCK.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/BargeIn/Tx_ControlParams_WIDEBAND_BLUETOOTH_SCO_HEADSET.txt:system/vendor/etc/nxp/BargeIn/Tx_ControlParams_WIDEBAND_BLUETOOTH_SCO_HEADSET.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/BargeIn/Tx_ControlParams_WIDEBAND_SPEAKER.txt:system/vendor/etc/nxp/BargeIn/Tx_ControlParams_WIDEBAND_SPEAKER.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/BargeIn/Tx_ControlParams_WIDEBAND_EARPIECE.txt:system/vendor/etc/nxp/BargeIn/Tx_ControlParams_WIDEBAND_EARPIECE.txt \
    $(VENDOR_DIR)/vendor/etc/nxp/BargeIn/Tx_ControlParams_WIDEBAND_WIRED_HEADPHONE.txt:system/vendor/etc/nxp/BargeIn/Tx_ControlParams_WIDEBAND_WIRED_HEADPHONE.txt

# PenSDK-5.1.0 libsec
PRODUCT_COPY_FILES += \
    $(VENDOR_DIR)/lib/PenSDK-5.1.0/libSPenEngine.so:system/lib/libSPenEngine.so \
    $(VENDOR_DIR)/lib/PenSDK-5.1.0/libSPenChineseBrushBig.so:system/lib/libSPenChineseBrushBig.so \
    $(VENDOR_DIR)/lib/PenSDK-5.1.0/libSPenBrush.so:system/lib/libSPenBrush.so \
    $(VENDOR_DIR)/lib/PenSDK-5.1.0/libSDK.so:system/lib/libSDK.so \
    $(VENDOR_DIR)/lib/PenSDK-5.1.0/libSPenCrayon.so:system/lib/libSPenCrayon.so \
    $(VENDOR_DIR)/lib/PenSDK-5.1.0/libSPenRecognizerSolver.so:system/lib/libSPenRecognizerSolver.so \
    $(VENDOR_DIR)/lib/PenSDK-5.1.0/libSPenGraphics.so:system/lib/libSPenGraphics.so \
    $(VENDOR_DIR)/lib/PenSDK-5.1.0/libSPenComposer.so:system/lib/libSPenComposer.so \
    $(VENDOR_DIR)/lib/PenSDK-5.1.0/libSPenWaterColorBrush.so:system/lib/libSPenWaterColorBrush.so \
    $(VENDOR_DIR)/lib/PenSDK-5.1.0/libSPenObliquePen.so:system/lib/libSPenObliquePen.so \
    $(VENDOR_DIR)/lib/PenSDK-5.1.0/libSPenEraser.so:system/lib/libSPenEraser.so \
    $(VENDOR_DIR)/lib/PenSDK-5.1.0/libgnustl_shared.so:system/lib/libgnustl_shared.so \
    $(VENDOR_DIR)/lib/PenSDK-5.1.0/libSPenModel.so:system/lib/libSPenModel.so \
    $(VENDOR_DIR)/lib/PenSDK-5.1.0/libSPenSDoc.so:system/lib/libSPenSDoc.so \
    $(VENDOR_DIR)/lib/PenSDK-5.1.0/libSPenRecognitionShape.so:system/lib/libSPenRecognitionShape.so \
    $(VENDOR_DIR)/lib/PenSDK-5.1.0/libSPenMontblancFountainPen.so:system/lib/libSPenMontblancFountainPen.so \
    $(VENDOR_DIR)/lib/PenSDK-5.1.0/libSPenFountainPen.so:system/lib/libSPenFountainPen.so \
    $(VENDOR_DIR)/lib/PenSDK-5.1.0/libSPenMarker.so:system/lib/libSPenMarker.so \
    $(VENDOR_DIR)/lib/PenSDK-5.1.0/libSPenSkia.so:system/lib/libSPenSkia.so \
    $(VENDOR_DIR)/lib/PenSDK-5.1.0/libSPenBeautify.so:system/lib/libSPenBeautify.so \
    $(VENDOR_DIR)/lib/PenSDK-5.1.0/libSPenRecognitionSignature.so:system/lib/libSPenRecognitionSignature.so \
    $(VENDOR_DIR)/lib/PenSDK-5.1.0/libSPenRecognizerContext.so:system/lib/libSPenRecognizerContext.so \
    $(VENDOR_DIR)/lib/PenSDK-5.1.0/libSPenMarker2.so:system/lib/libSPenMarker2.so \
    $(VENDOR_DIR)/lib/PenSDK-5.1.0/libSPenPencil3.so:system/lib/libSPenPencil3.so \
    $(VENDOR_DIR)/lib/PenSDK-5.1.0/libSPenGL.so:system/lib/libSPenGL.so \
    $(VENDOR_DIR)/lib/PenSDK-5.1.0/libSPenRecognitionText.so:system/lib/libSPenRecognitionText.so \
    $(VENDOR_DIR)/lib/PenSDK-5.1.0/libSPenBrushPen.so:system/lib/libSPenBrushPen.so \
    $(VENDOR_DIR)/lib/PenSDK-5.1.0/libSPenMontblancCalligraphyPen.so:system/lib/libSPenMontblancCalligraphyPen.so \
    $(VENDOR_DIR)/lib/PenSDK-5.1.0/libSPenRecognitionEquation.so:system/lib/libSPenRecognitionEquation.so \
    $(VENDOR_DIR)/lib/PenSDK-5.1.0/libSPenRecognizerShape.so:system/lib/libSPenRecognizerShape.so \
    $(VENDOR_DIR)/lib/PenSDK-5.1.0/libSPenRecognitionNRRSignature.so:system/lib/libSPenRecognitionNRRSignature.so \
    $(VENDOR_DIR)/lib/PenSDK-5.1.0/libSPenChineseBrush.so:system/lib/libSPenChineseBrush.so \
    $(VENDOR_DIR)/lib/PenSDK-5.1.0/libSPenRecognizer.so:system/lib/libSPenRecognizer.so \
    $(VENDOR_DIR)/lib/PenSDK-5.1.0/libSPenCrayon2.so:system/lib/libSPenCrayon2.so \
    $(VENDOR_DIR)/lib/PenSDK-5.1.0/libSPenControl.so:system/lib/libSPenControl.so \
    $(VENDOR_DIR)/lib/PenSDK-5.1.0/libSPenMagicPen.so:system/lib/libSPenMagicPen.so \
    $(VENDOR_DIR)/lib/PenSDK-5.1.0/libSPenInkPen.so:system/lib/libSPenInkPen.so \
    $(VENDOR_DIR)/lib/PenSDK-5.1.0/libSPenInit.so:system/lib/libSPenInit.so \
    $(VENDOR_DIR)/lib/PenSDK-5.1.0/libSPenPencil.so:system/lib/libSPenPencil.so \
    $(VENDOR_DIR)/lib/PenSDK-5.1.0/libSPenOilBrush2.so:system/lib/libSPenOilBrush2.so \
    $(VENDOR_DIR)/lib/PenSDK-5.1.0/libSPenOilBrush3.so:system/lib/libSPenOilBrush3.so \
    $(VENDOR_DIR)/lib/PenSDK-5.1.0/libSPenRecognitionWorker.so:system/lib/libSPenRecognitionWorker.so \
    $(VENDOR_DIR)/lib/PenSDK-5.1.0/libSPenAirBrushPen.so:system/lib/libSPenAirBrushPen.so \
    $(VENDOR_DIR)/lib/PenSDK-5.1.0/libSPenRecognizerDocument.so:system/lib/libSPenRecognizerDocument.so \
    $(VENDOR_DIR)/lib/PenSDK-5.1.0/libSPenPencil2.so:system/lib/libSPenPencil2.so \
    $(VENDOR_DIR)/lib/PenSDK-5.1.0/libSPenPluginFW.so:system/lib/libSPenPluginFW.so \
    $(VENDOR_DIR)/lib/PenSDK-5.1.0/libSPenBase.so:system/lib/libSPenBase.so

# CameraSDK_v1.3.0
PRODUCT_COPY_FILES += \
    $(VENDOR_DIR)/lib/CameraSDK_v1.3.0/libscamera_util.so:system/lib/libscamera_util.so \
    $(VENDOR_DIR)/lib/CameraSDK_v1.3.0/libsrc_haze_removal_capture.so:system/lib/libsrc_haze_removal_capture.so \
    $(VENDOR_DIR)/lib/CameraSDK_v1.3.0/libscamera_core.so:system/lib/libscamera_core.so \
    $(VENDOR_DIR)/lib/CameraSDK_v1.3.0/libscamera_jni.so:system/lib/libscamera_jni.so \
    $(VENDOR_DIR)/lib/CameraSDK_v1.3.0/libdmcFaceEngine.so:system/lib/libdmcFaceEngine.so \
    $(VENDOR_DIR)/lib/CameraSDK_v1.3.0/libsrc_haze_removal_preview.so:system/lib/libsrc_haze_removal_preview.so \
    $(VENDOR_DIR)/lib/CameraSDK_v1.3.0/libscamera_dof.so:system/lib/libscamera_dof.so \
    $(VENDOR_DIR)/lib/CameraSDK_v1.3.0/libscamera_ipx.so:system/lib/libscamera_ipx.so \
    $(VENDOR_DIR)/lib/CameraSDK_v1.3.0/libscamera_panorama.so:system/lib/libscamera_panorama.so

# SSWAP+CBD
PRODUCT_COPY_FILES += \
    $(VENDOR_DIR)/sbin/sswap:root/sbin/sswap
